# =============================================================================
# Pipeline DevSecOps - Taskfile.yml
# =============================================================================
# Phases du cycle de vie:
#   1. pre-commit      - Vérifications rapides avant chaque commit
#   2. branch-feature   - Vérifications approfondies sur branche feature
#   3. pull-request     - Validation complète avant merge (CI/CD)
#   4. staging          - Déploiement et validation en pré-production
#   5. production       - Déploiement sécurisé en production
#   6. nightly          - Analyses approfondies planifiées
#
# Usage:
#   task <phase>          - Exécuter une phase complète
#   task <sous-tâche>     - Exécuter une tâche individuelle
#   task --list           - Lister toutes les tâches disponibles
#   task setup            - Installer tous les outils nécessaires
# =============================================================================

version: '3'

dotenv: ['.env']

vars:
  # --- Environnement ---
  CI: '{{.CI | default "false"}}'
  NODE_ENV: '{{.NODE_ENV | default "development"}}'

  # --- Docker ---
  DOCKER_REGISTRY: '{{.DOCKER_REGISTRY | default "localhost:5000"}}'
  IMAGE_NAME: '{{.IMAGE_NAME | default "devsecops-api"}}'
  IMAGE_TAG: '{{.IMAGE_TAG | default "latest"}}'
  DOCKERFILE: '{{.DOCKERFILE | default "Dockerfile"}}'

  # --- SonarQube ---
  SONAR_URL: '{{.SONAR_URL | default "http://localhost:9000"}}'
  SONAR_PROJECT_KEY: '{{.SONAR_PROJECT_KEY | default "demo-devsecops-api-j1"}}'

  # --- Staging / Production ---
  STAGING_URL: '{{.STAGING_URL | default "http://localhost:3001"}}'
  PROD_URL: '{{.PROD_URL | default "http://localhost:3000"}}'
  STAGING_COMPOSE: '{{.STAGING_COMPOSE | default "docker-compose.staging.yml"}}'
  PROD_COMPOSE: '{{.PROD_COMPOSE | default "docker-compose.prod.yml"}}'

  # --- Seuils ---
  COVERAGE_THRESHOLD: '{{.COVERAGE_THRESHOLD | default "60"}}'
  TRIVY_SEVERITY: '{{.TRIVY_SEVERITY | default "HIGH,CRITICAL"}}'

  # --- Rapports ---
  REPORTS_DIR: '{{.REPORTS_DIR | default "reports"}}'

# =============================================================================
# PHASE 1 : PRE-COMMIT
# Vérifications rapides avant chaque commit (~30s)
# =============================================================================

tasks:

  pre-commit:
    desc: "[Phase 1] Vérifications pré-commit (lint, format, secrets, tests unitaires)"
    cmds:
      - task: lint
      - task: format-check
      - task: secrets-scan
      - task: unit-test

  lint:
    desc: "Analyse statique du code avec ESLint"
    cmds:
      - npx eslint src/ --ext .js --format {{if eq .CI "true"}}json{{else}}stylish{{end}} {{if eq .CI "true"}}--output-file {{.REPORTS_DIR}}/eslint-report.json{{end}}
    sources:
      - src/**/*.js

  format-check:
    desc: "Vérification du formatage avec Prettier"
    cmds:
      - npx prettier --check "src/**/*.js"

  secrets-scan:
    desc: "Détection de secrets avec gitleaks"
    preconditions:
      - sh: command -v gitleaks
        msg: "gitleaks n'est pas installé. Lancez 'task setup' ou installez-le : https://github.com/gitleaks/gitleaks"
    cmds:
      - mkdir -p {{.REPORTS_DIR}}
      - gitleaks detect --source . --verbose --redact --report-format json --report-path {{.REPORTS_DIR}}/gitleaks-report.json
    ignore_error: true

  unit-test:
    desc: "Tests unitaires rapides (fail-fast)"
    cmds:
      - npx jest --bail --forceExit --detectOpenHandles {{if eq .CI "true"}}--ci --reporters=default --reporters=jest-junit{{end}}
    env:
      NODE_ENV: test
      JEST_JUNIT_OUTPUT_DIR: "{{.REPORTS_DIR}}"

# =============================================================================
# PHASE 2 : FEATURE BRANCH
# Vérifications approfondies pendant le développement (~2-5min)
# =============================================================================

  branch-feature:
    desc: "[Phase 2] Vérifications sur branche feature (pre-commit + SAST + SCA)"
    cmds:
      - task: pre-commit
      - task: sast
      - task: npm-audit
      - task: license-check
      - task: outdated

  sast:
    desc: "Analyse SAST avec Semgrep (règles OWASP)"
    preconditions:
      - sh: command -v semgrep
        msg: "Semgrep n'est pas installé. Lancez 'task setup' ou: pip install semgrep"
    env:
      PYTHONUTF8: "1"
      PYTHONIOENCODING: utf-8
    cmds:
      - mkdir -p {{.REPORTS_DIR}}
      - semgrep scan --config=auto --config=p/owasp-top-ten --config=p/nodejs --config=p/javascript {{if eq .CI "true"}}--json --output={{.REPORTS_DIR}}/semgrep-report.json{{else}}--verbose{{end}} src/
    ignore_error: true

  npm-audit:
    desc: "Scan des vulnérabilités dans les dépendances (npm audit)"
    cmds:
      - npm audit {{if eq .CI "true"}}--json > {{.REPORTS_DIR}}/npm-audit-report.json || true{{else}}--audit-level=moderate{{end}}

  license-check:
    desc: "Vérification de conformité des licences"
    cmds:
      - npx license-checker --summary --failOn "GPL-3.0;AGPL-3.0;UNLICENSED" {{if eq .CI "true"}}--json > {{.REPORTS_DIR}}/license-report.json{{end}}

  outdated:
    desc: "Détection des dépendances obsolètes"
    cmds:
      - npm outdated || true

# =============================================================================
# PHASE 3 : PULL REQUEST
# Validation complète avant merge (~5-15min)
# =============================================================================

  pull-request:
    desc: "[Phase 3] Validation complète pour Pull Request (CI/CD)"
    cmds:
      - task: branch-feature
      - task: integration-test
      - task: coverage
      - task: sonarqube-scan
      - task: docker-build
      - task: trivy-image
      - task: snyk-test

  integration-test:
    desc: "Tests d'intégration API (Jest + Supertest)"
    cmds:
      - npx jest --testPathPattern="integration|e2e" --forceExit --detectOpenHandles {{if eq .CI "true"}}--ci{{end}}
    env:
      NODE_ENV: test

  coverage:
    desc: "Couverture de code avec seuil minimum ({{.COVERAGE_THRESHOLD}}%)"
    cmds:
      - npx jest --coverage --coverageReporters=text --coverageReporters=lcov --coverageReporters=json-summary --coverageDirectory=coverage --forceExit --detectOpenHandles {{if eq .CI "true"}}--ci{{end}}
      - |
        echo "=== Vérification du seuil de couverture ({{.COVERAGE_THRESHOLD}}%) ==="
        if [ -f coverage/coverage-summary.json ]; then
          ACTUAL=$(node -e "const c=require('./coverage/coverage-summary.json');console.log(Math.round(c.total.lines.pct))")
          echo "Couverture actuelle: ${ACTUAL}%"
          if [ "$ACTUAL" -lt "{{.COVERAGE_THRESHOLD}}" ]; then
            echo "ÉCHEC: Couverture (${ACTUAL}%) inférieure au seuil ({{.COVERAGE_THRESHOLD}}%)"
            exit 1
          fi
          echo "OK: Couverture suffisante"
        else
          echo "ATTENTION: Pas de rapport de couverture généré"
        fi
    env:
      NODE_ENV: test

  sonarqube-scan:
    desc: "Analyse de qualité avec SonarQube"
    preconditions:
      - sh: command -v sonar-scanner
        msg: "sonar-scanner n'est pas installé. Lancez 'task setup' ou: npm i -g sonar-scanner"
    cmds:
      - sonar-scanner -Dsonar.host.url={{.SONAR_URL}} -Dsonar.projectKey={{.SONAR_PROJECT_KEY}} {{if ne .SONAR_TOKEN ""}} -Dsonar.token={{.SONAR_TOKEN}}{{end}}

  docker-build:
    desc: "Build de l'image Docker"
    preconditions:
      - sh: command -v docker
        msg: "Docker n'est pas installé."
    cmds:
      - docker build -t {{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.IMAGE_TAG}} -f {{.DOCKERFILE}} .
      - echo "Image construite - {{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.IMAGE_TAG}}"

  trivy-image:
    desc: "Scan de vulnérabilités de l'image Docker avec Trivy"
    preconditions:
      - sh: command -v trivy
        msg: "Trivy n'est pas installé. Lancez 'task setup' ou: https://aquasecurity.github.io/trivy"
    cmds:
      - mkdir -p {{.REPORTS_DIR}}
      - trivy image --severity {{.TRIVY_SEVERITY}} --format {{if eq .CI "true"}}json --output {{.REPORTS_DIR}}/trivy-image-report.json{{else}}table{{end}} {{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.IMAGE_TAG}}

  snyk-test:
    desc: "Analyse approfondie des dépendances avec Snyk"
    preconditions:
      - sh: command -v snyk
        msg: "Snyk n'est pas installé. Lancez 'task setup' ou: npm i -g snyk && snyk auth"
    cmds:
      - snyk test {{if eq .CI "true"}}--json > {{.REPORTS_DIR}}/snyk-report.json || true{{else}}--severity-threshold=medium{{end}}
